spring.application.name=payment-service
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8008/server/eureka/

# Redis Properties
spring.cache.type=redis
spring.cache.redis.cache-null-values=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=true